import { CrowsContentImport, IMPORT_PACKS } from "./module/import-content.mjs";
import { CrowsChatActions } from "./module/chat-actions.mjs";
import { CrowDataModel, EquipmentDataModel, MonsterDataModel, LootDataModel, AttackDataModel, TraitDataModel } from "./module/data-models.mjs";
import { CrowsActor, CrowsItem } from "./module/documents.mjs";
import { CrowsActorSheet, EXPERTISES_CONFIG } from "./module/sheets/actor-sheet.mjs";
import { CrowsMonsterSheet } from "./module/sheets/monster-sheet.mjs";
import { CrowsLootSheet } from "./module/sheets/loot-sheet.mjs";
import { CrowsItemSheet } from "./module/sheets/item-sheet.mjs";
import { VillageDataModel, VillageEntryDataModel } from "./module/village-data-models.mjs";
import { BoonDataModel } from "./module/boon-data-model.mjs";
import { CrowsVillageSheet } from "./module/sheets/village-sheet.mjs";
import { CrowsVillageEntrySheet } from "./module/sheets/village-entry-sheet.mjs";
import { CrowsLoot } from "./module/loot.mjs";
import { CrowsLootDrag } from "./module/loot-drag.mjs";
import { CrowsToken } from "./module/token.mjs";
import { CrowsDungeonTimer } from "./module/apps/dungeon-timer.mjs";
import { CrowsImporter } from "./module/apps/importer.mjs";
import { CrowsSetupGuide } from "./module/apps/setup-guide.mjs";
import { repairWorldIcons } from "./module/icon-repairs.mjs";
import { CrowsCharacterCreator, addCharacterCreatorButton, addCharacterCreatorToDocumentDirectory,
  refreshCharacterCreatorButtons } from "./module/apps/character-creator.mjs";

Hooks.on("renderActorDirectory", addCharacterCreatorButton);
Hooks.on("renderDocumentDirectory", addCharacterCreatorToDocumentDirectory);
Hooks.on("renderSidebar", refreshCharacterCreatorButtons);
Hooks.once("ready", refreshCharacterCreatorButtons);
Hooks.once("ready", () => CrowsSetupGuide.showOnFirstVisit());
Hooks.on("updateUser", user => {
  if (user.id === game.user.id) refreshCharacterCreatorButtons();
});
Hooks.on("updateSetting", setting => {
  if (setting.key === "core.permissions") refreshCharacterCreatorButtons();
});

Hooks.once("init", async () => {
  console.log("Crows | Initializing MCDM Crows System (Playtest 2 & Physical Ground Loot)");

  // Configure custom Document implementations
  CONFIG.Actor.documentClass = CrowsActor;
  CONFIG.Item.documentClass = CrowsItem;
  CONFIG.Token.objectClass = CrowsToken;

  // Configure System Data Models
  CONFIG.Actor.dataModels = {
    crow: CrowDataModel,
    monster: MonsterDataModel,
    loot: LootDataModel,
    village: VillageDataModel
  };
  CONFIG.Item.dataModels = {
    equipment: EquipmentDataModel,
    attack: AttackDataModel,
    trait: TraitDataModel,
    villageEntry: VillageEntryDataModel,
    boon: BoonDataModel
  };

  // Register Sheets
  Actors.unregisterSheet("core", ActorSheet);
  Actors.registerSheet("crows", CrowsActorSheet, { types: ["crow"], makeDefault: true });
  Actors.registerSheet("crows", CrowsMonsterSheet, { types: ["monster"], makeDefault: true });
  Actors.registerSheet("crows", CrowsLootSheet, { types: ["loot"], makeDefault: true });
  Actors.registerSheet("crows", CrowsVillageSheet, { types: ["village"], makeDefault: true });

  Items.unregisterSheet("core", ItemSheet);
  Items.registerSheet("crows", CrowsItemSheet, { types: ["equipment", "attack", "trait", "boon"], makeDefault: true });
  Items.registerSheet("crows", CrowsVillageEntrySheet, { types: ["villageEntry"], makeDefault: true });

  // Register Synchronized World Setting for Dungeon Turn Timer
  game.settings.register("fvtt-crows-system", "dungeonTimerState", {
    name: "Dungeon Timer State",
    hint: "Synchronized state for the real-world MCDM Crows Dungeon Turn timer.",
    scope: "world",
    config: false,
    type: Object,
    default: {
      turn: 1,
      durationMinutes: 30,
      remainingSeconds: 1800,
      isRunning: false,
      en: 9,
      lastTick: Date.now()
    },
    onChange: () => {
      if (game.crows?.timerHUD) {
        game.crows.timerHUD.render();
      }
    }
  });

  // Ground loot chat settings
  CrowsLoot.registerSettings();

  game.settings.registerMenu("fvtt-crows-system", "setupGuide", {
    name: "Start Here", label: "Open Setup Guide",
    hint: "A friendly walkthrough: Python, your PDF folder, and importing the playtest content.",
    icon: "fas fa-book-open", type: CrowsSetupGuide, restricted: false
  });

  // GM menu: import the locally generated playtest content
  game.settings.registerMenu("fvtt-crows-system", "importer", {
    name: "Import Playtest Content",
    label: "Open Importer",
    hint: "Import the compendium data generated by tools/build_all.py from your own copy of the MCDM playtest packet.",
    icon: "fas fa-download",
    type: CrowsImporter,
    restricted: true
  });

  // Available to players as well as GMs; creation checks Actor permissions.
  game.settings.registerMenu("fvtt-crows-system", "characterCreator", {
    name: "Character Creator", label: "Create a Crow", hint: "Create a new crow from your locally generated playtest content.",
    icon: "fas fa-feather", type: CrowsCharacterCreator, restricted: false
  });

  // Playtest 2 Status Effects
  CONFIG.statusEffects = [
    {
      id: "weakened",
      name: "Weakened",
      img: "icons/skills/melee/unarmed-punch-fist.webp",
      description: "You take a bane on all tests. Ends at the end of a Dungeon Turn (DT)."
    },
    {
      id: "vulnerable",
      name: "Vulnerable",
      img: "icons/skills/wounds/injury-pain-body-orange.webp",
      description: "Each time you take damage, you take an additional 1d6 damage. Ends at the end of a DT."
    },
    {
      id: "blessed",
      name: "Blessed",
      img: "icons/magic/holy/prayer-hands-glowing-yellow.webp",
      description: "You gain an edge on all tests, and attacks deal additional damage equal to the characteristic used. Ends at the end of a DT."
    },
    {
      id: "grabbed",
      name: "Grabbed",
      img: "icons/weapons/fist/claw-grey-black.webp",
      description: "Speed is 0, can't flank, attacks against you gain an edge."
    },
    {
      id: "prone",
      name: "Prone",
      img: "icons/svg/falling.svg",
      description: "Speed halved, bane on melee attacks, melee attacks against you gain edge, ranged attacks against you take bane."
    },
    {
      id: "unconscious",
      name: "Unconscious",
      img: "icons/svg/unconscious.svg",
      description: "Prone, speed 0, no actions/maneuvers, automatic doom on Agility/Strength tests, double bane on Mind notices."
    }
  ];

  // Trackable attributes for tokens
  CONFIG.Actor.trackableAttributes = {
    crow: {
      bar: ["stamina"],
      value: ["derivedSpeed", "totalWounds", "carriedGold"]
    },
    monster: {
      bar: ["stamina"],
      value: []
    },
    loot: {
      bar: [],
      value: ["coins"]
    }
  };
  await loadTemplates([
    "systems/fvtt-crows-system/templates/inventory-controls.html",
    "systems/fvtt-crows-system/templates/usage-dice.html"
  ]);
});

// Register Canvas Drop Hook for Ground Loot
Hooks.on("dropCanvasData", (canvas, data) => {
  if (data.type !== "Item") return;
  CrowsLoot.onDropCanvasData(canvas, data).catch(err => {
    console.error("Crows | Item drop failed", err);
    ui.notifications.error("Could not move the item.");
  });
  return false;
});
Hooks.on("canvasReady", () => CrowsLootDrag.start());
Hooks.on("canvasTearDown", () => CrowsLootDrag.stop());

// Crow token defaults apply only at creation, preserving explicit settings on copies/imports.
Hooks.on("preCreateActor", (doc, data) => {
  if (doc.type !== "crow") return;
  const creationData = foundry.utils.expandObject(data);
  const defaults = {
    "prototypeToken.actorLink": true,
    "prototypeToken.sight.enabled": true,
    "prototypeToken.disposition": CONST.TOKEN_DISPOSITIONS.FRIENDLY,
    "prototypeToken.bar1.attribute": "stamina",
    "prototypeToken.displayBars": CONST.TOKEN_DISPLAY_MODES.OWNER,
    "prototypeToken.displayName": CONST.TOKEN_DISPLAY_MODES.HOVER,
    "prototypeToken.lockRotation": true
  };
  const updates = {};
  for (const [path, value] of Object.entries(defaults)) {
    if (foundry.utils.getProperty(creationData, path) === undefined) updates[path] = value;
  }
  if (Object.keys(updates).length) doc.updateSource(updates);
});

// Set initial loot visibility and Ref-controlled contents access.
Hooks.on("preCreateActor", (doc, data) => CrowsLoot.onPreCreateActor(doc, data));

// Interactive Chat Handler: Apply Expertise Post-Roll
Hooks.on("renderChatMessage", (message, html, data) => {
  CrowsChatActions.bind(message, html);
  // Historical cards lack trustworthy roll context; leave their text intact and ask for a new roll.
  html.find(".crows-apply-expertise-btn").click(event => {
    event.preventDefault();
    ui.notifications.warn("This older roll has no saved action state. Roll again to apply expertise.");
  });

  // Miasma Chat Handler: Gain Cruelty & Trigger Effect Roll
  html.find(".crows-miasma-gain-cruelty-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const actorId = btn.data("actorId");
    const actor = (message.speaker?.token ? game.scenes.get(message.speaker.scene)?.tokens.get(message.speaker.token)?.actor : game.actors.get(actorId));
    if (!actor) {
      ui.notifications.error("Actor not found.");
      return;
    }
    if (!actor.isOwner && !game.user.isGM) {
      ui.notifications.warn("You do not have permission for this actor.");
      return;
    }

    const newCruelty = await actor.adjustCruelty(1);
    ui.notifications.warn(`${actor.name}'s Cruelty increased to ${newCruelty}!`);
    btn.prop("disabled", true).text(`+1 Cruelty Added (Now ${newCruelty})`);

    // Trigger Miasma effect roll
    if (actor.sheet && actor.sheet._onRollMiasmaEffect) {
      await actor.sheet._onRollMiasmaEffect();
    }
  });

  // Miasma Chat Handler: Clear Cruelty
  html.find(".crows-miasma-clear-cruelty-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const actorId = btn.data("actorId");
    const actor = (message.speaker?.token ? game.scenes.get(message.speaker.scene)?.tokens.get(message.speaker.token)?.actor : game.actors.get(actorId));
    if (!actor) {
      ui.notifications.error("Actor not found.");
      return;
    }
    if (!actor.isOwner && !game.user.isGM) {
      ui.notifications.warn("You do not have permission for this actor.");
      return;
    }

    await actor.clearCruelty();
    ui.notifications.info(`${actor.name} purged all levels of cruelty (Cruelty: 0).`);
    btn.prop("disabled", true).text(`Cruelty Purged to 0`);
  });

  // Miasma Chat Handler: Apply Miasma Effect to Sheet
  html.find(".crows-miasma-apply-effect-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const actorId = btn.data("actorId");
    const actor = (message.speaker?.token ? game.scenes.get(message.speaker.scene)?.tokens.get(message.speaker.token)?.actor : game.actors.get(actorId));
    if (!actor) {
      ui.notifications.error("Actor not found.");
      return;
    }
    if (!actor.isOwner && !game.user.isGM) {
      ui.notifications.warn("You do not have permission for this actor.");
      return;
    }

    const title = btn.data("title");
    const firstEffect = decodeURIComponent(btn.data("first") || "");
    const secondEffect = decodeURIComponent(btn.data("second") || "");
    const rollTotal = parseInt(btn.data("roll"), 10) || 1;

    await actor.addMiasmaEffect({ title, firstEffect, secondEffect, rollTotal });
    ui.notifications.info(`Added "${title}" to ${actor.name}'s active Miasma effects.`);
    btn.prop("disabled", true).html(`<i class="fas fa-check"></i> Added to Character Sheet`);
  });

  // Interactive Chat Handler: Apply Damage to Target Dialog
  html.find(".crows-apply-damage-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const damageAmount = parseInt(btn.data("damageAmount"), 10) || 1;
    const targetActorId = btn.data("targetActorId");
    const targetTokenId = btn.data("targetTokenId");

    // Legacy cards: token identity takes precedence and a deleted token never falls back to its base actor.
    let targetActor = targetTokenId
      ? game.scenes.get(message.speaker?.scene)?.tokens.get(targetTokenId)?.actor
      : targetActorId ? game.actors.get(targetActorId)
      : Array.from(game.user.targets)[0]?.actor || canvas.tokens.controlled[0]?.actor;

    if (!targetActor) {
      ui.notifications.warn("No target specified or currently selected. Please target or select a token to apply damage.");
      return;
    }

    if (!targetActor.isOwner && !game.user.isGM) {
      ui.notifications.warn(`You do not have permission to manage damage for ${targetActor.name}.`);
      return;
    }

    if (targetActor.openDamageAllocationDialog) {
      targetActor.openDamageAllocationDialog(damageAmount);
    } else {
      targetActor.applyDamage(damageAmount);
    }
  });
});

async function importContent(packs) {
  const report = await CrowsContentImport.run(packs);
  const summary = CrowsContentImport.describe(report);
  if (report.some(row => row.error)) ui.notifications.error(summary);
  else ui.notifications.info(summary);
  return report;
}

Hooks.once("ready", () => {
  // Loot transfers requested by players are executed by the active GM's client
  CrowsLoot.activateSocket();
  CrowsChatActions.activate([...EXPERTISES_CONFIG.general, ...EXPERTISES_CONFIG.spellcasting, ...EXPERTISES_CONFIG.weapon]);
  repairWorldIcons().catch(error => console.error("Crows | Icon repair failed", error));
  CrowsLoot.migrateGold().catch(error => {
    console.error("Crows | Gold conversion failed", error);
    ui.notifications.error("Gold conversion could not finish. Check the console before retrying.");
  });

  // Initialize and render the Hourglass Dungeon Turn HUD
  const timerHUD = new CrowsDungeonTimer();
  timerHUD.render(true);

  // Expose system helper utilities
  game.crows = {
    createCrow: () => new CrowsCharacterCreator().render(true),
    timerHUD: timerHUD,

    /**
     * Hourglass Dungeon Turn Timer API
     */
    timer: {
      start: async () => CrowsDungeonTimer.updateState({ isRunning: true }),
      pause: async () => CrowsDungeonTimer.updateState({ isRunning: false }),
      toggle: async () => {
        const state = CrowsDungeonTimer.getState();
        return CrowsDungeonTimer.updateState({ isRunning: !state.isRunning });
      },
      reset: async () => {
        const state = CrowsDungeonTimer.getState();
        return CrowsDungeonTimer.updateState({
          resolvingTurn: false,
          remainingSeconds: (state.durationMinutes || 30) * 60,
          isRunning: false
        });
      },
      nextTurn: async () => timerHUD.endTurn(),
      show: () => timerHUD.render(true),
      hide: () => timerHUD.close()
    },

    /**
     * Canvas Ground Loot API
     */
    loot: CrowsLoot,
    scatterLoot: CrowsLoot.scatterItemsOnCanvas,
    createLootToken: CrowsLoot.createLootToken,

    /**
     * Rolls a d10 Dungeon Encounter Check (Playtest 2 rule)
     */
    rollEncounterCheck: async (en = 9) => {
      const roll = new Roll("1d10");
      await roll.evaluate();
      const result = roll.total;

      let outcomeHtml = "";
      if (result === 10) {
        outcomeHtml = `<div class="outcome doom"><i class="fas fa-skull-crossbones"></i> IMMEDIATE ENCOUNTER! (Rolled 10)</div>
                       <p class="flavor-sub">Monsters ambush or stumble upon the party right now!</p>`;
      } else if (result >= en) {
        outcomeHtml = `<div class="outcome mixed"><i class="fas fa-exclamation-triangle"></i> ENCOUNTER WARNING (Rolled ${result} &ge; EN ${en})</div>
                       <p class="flavor-sub">The party detects signs/sounds of a coming encounter. The encounter occurs during the next Dungeon Turn.</p>`;
      } else {
        outcomeHtml = `<div class="outcome success"><i class="fas fa-shield-alt"></i> ALL QUIET (Rolled ${result} &lt; EN ${en})</div>
                       <p class="flavor-sub">No encounter this turn.</p>`;
      }

      const content = `
        <div class="crows-roll-card">
          <div class="card-header danger">
            <i class="fas fa-dungeon"></i> Dungeon Encounter Check (EN ${en})
          </div>
          <div class="card-body">
            <div class="dice-roll-total">D10 Check: <strong>${result}</strong> vs EN ${en}</div>
            ${outcomeHtml}
          </div>
        </div>
      `;

      await roll.toMessage({
        flavor: `Dungeon Encounter Check (EN ${en})`,
        content: content
      });
    },

    /**
     * Rolls a 1d6 Chaos Roll for non-doom Tier 1 spellcasting
     */
    rollChaos: async () => {
      const roll = new Roll("1d6");
      await roll.evaluate();
      const result = roll.total;

      let outcomeHtml = "";
      if (result === 1) {
        outcomeHtml = `<div class="outcome doom"><i class="fas fa-bolt"></i> MAGICAL BACKLASH! (Rolled 1)</div>
                       <p class="flavor-sub">Roll 1d100 + Spell Rank on the Backlash Table in The Rules Book!</p>`;
      } else {
        outcomeHtml = `<div class="outcome success"><i class="fas fa-check-circle"></i> SAFE (Rolled ${result})</div>
                       <p class="flavor-sub">The chaos recedes without triggering a backlash.</p>`;
      }

      const content = `
        <div class="crows-roll-card">
          <div class="card-header">
            <i class="fas fa-magic"></i> Chaos Roll (1d6)
          </div>
          <div class="card-body">
            <div class="dice-roll-total">Result: <strong>${result}</strong></div>
            ${outcomeHtml}
          </div>
        </div>
      `;

      await roll.toMessage({
        flavor: `Chaos Roll (1d6)`,
        content: content
      });
    },

    importEquipment: () => importContent([IMPORT_PACKS[0]]),
    importDungeonLoot: () => importContent([IMPORT_PACKS[1]]),
    importTraits: () => importContent([IMPORT_PACKS[2]]),
    importMonsters: () => importContent([IMPORT_PACKS[3]]),
    importPlaytestItems: () => importContent(IMPORT_PACKS)
  };
});
