import { CrowDataModel, EquipmentDataModel, MonsterDataModel, LootDataModel, AttackDataModel, TraitDataModel } from "./module/data-models.mjs";
import { CrowsActor, CrowsItem } from "./module/documents.mjs";
import { CrowsActorSheet, EXPERTISES_CONFIG } from "./module/sheets/actor-sheet.mjs";
import { CrowsMonsterSheet } from "./module/sheets/monster-sheet.mjs";
import { CrowsLootSheet } from "./module/sheets/loot-sheet.mjs";
import { CrowsItemSheet } from "./module/sheets/item-sheet.mjs";
import { CrowsLoot } from "./module/loot.mjs";
import { CrowsDungeonTimer } from "./module/apps/dungeon-timer.mjs";
import { CrowsImporter } from "./module/apps/importer.mjs";

Hooks.once("init", () => {
  console.log("Crows | Initializing MCDM Crows System (Playtest 2 & Physical Ground Loot)");

  // Configure custom Document implementations
  CONFIG.Actor.documentClass = CrowsActor;
  CONFIG.Item.documentClass = CrowsItem;

  // Configure System Data Models
  CONFIG.Actor.dataModels = {
    crow: CrowDataModel,
    monster: MonsterDataModel,
    loot: LootDataModel
  };
  CONFIG.Item.dataModels = {
    equipment: EquipmentDataModel,
    attack: AttackDataModel,
    trait: TraitDataModel
  };

  // Register Sheets
  Actors.unregisterSheet("core", ActorSheet);
  Actors.registerSheet("crows", CrowsActorSheet, { types: ["crow"], makeDefault: true });
  Actors.registerSheet("crows", CrowsMonsterSheet, { types: ["monster"], makeDefault: true });
  Actors.registerSheet("crows", CrowsLootSheet, { types: ["loot"], makeDefault: true });

  Items.unregisterSheet("core", ItemSheet);
  Items.registerSheet("crows", CrowsItemSheet, { makeDefault: true });

  // Register Synchronized World Setting for Dungeon Turn Timer
  game.settings.register("fvtt-crows-system", "dungeonTimerState", {
    name: "Dungeon Timer State",
    hint: "Synchronized state for the real-world MCDM Crows Dungeon Turn timer.",
    scope: "world",
    config: false,
    type: Object,
    default: {
      turn: 1,
      durationMinutes: 30,
      remainingSeconds: 1800,
      isRunning: false,
      en: 9,
      lastTick: Date.now()
    },
    onChange: () => {
      if (game.crows?.timerHUD) {
        game.crows.timerHUD.render();
      }
    }
  });

  // GM menu: import the locally generated playtest content
  game.settings.registerMenu("fvtt-crows-system", "importer", {
    name: "Import Playtest Content",
    label: "Open Importer",
    hint: "Import the compendium data generated by tools/build_all.py from your own copy of the MCDM playtest packet.",
    icon: "fas fa-download",
    type: CrowsImporter,
    restricted: true
  });

  // Playtest 2 Status Effects
  CONFIG.statusEffects = [
    {
      id: "weakened",
      name: "Weakened",
      img: "icons/skills/melee/unarmed-punch-fist.webp",
      description: "You take a bane on all tests. Ends at the end of a Dungeon Turn (DT)."
    },
    {
      id: "vulnerable",
      name: "Vulnerable",
      img: "icons/skills/wounds/injury-bleeding-body-red.webp",
      description: "Each time you take damage, you take an additional 1d6 damage. Ends at the end of a DT."
    },
    {
      id: "blessed",
      name: "Blessed",
      img: "icons/magic/holy/prayer-hands-glowing-yellow.webp",
      description: "You gain an edge on all tests, and attacks deal additional damage equal to the characteristic used. Ends at the end of a DT."
    },
    {
      id: "grabbed",
      name: "Grabbed",
      img: "icons/skills/melee/unarmed-claws-beast.webp",
      description: "Speed is 0, can't flank, attacks against you gain an edge."
    },
    {
      id: "prone",
      name: "Prone",
      img: "icons/skills/movement/feet-fall-down-orange.webp",
      description: "Speed halved, bane on melee attacks, melee attacks against you gain edge, ranged attacks against you take bane."
    },
    {
      id: "unconscious",
      name: "Unconscious",
      img: "icons/svg/unconscious.svg",
      description: "Prone, speed 0, no actions/maneuvers, automatic doom on Agility/Strength tests, double bane on Mind notices."
    }
  ];

  // Trackable attributes for tokens
  CONFIG.Actor.trackableAttributes = {
    crow: {
      bar: ["stamina"],
      value: ["derivedSpeed", "totalWounds", "coins"]
    },
    monster: {
      bar: ["stamina"],
      value: []
    },
    loot: {
      bar: [],
      value: ["coins"]
    }
  };
});

// Register Canvas Drop Hook for Ground Loot
Hooks.on("dropCanvasData", (canvas, data) => {
  return CrowsLoot.onDropCanvasData(canvas, data);
});

// Interactive Chat Handler: Apply Expertise Post-Roll
Hooks.on("renderChatMessage", (message, html, data) => {
  html.find(".crows-apply-expertise-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const actorId = btn.data("actorId");
    const actor = game.actors.get(actorId) || (message.speaker?.token ? canvas.tokens.get(message.speaker.token)?.actor : null);
    if (!actor) {
      ui.notifications.error("Actor could not be found for this roll.");
      return;
    }

    if (!actor.isOwner && !game.user.isGM) {
      ui.notifications.warn("You do not have permission to apply expertises for this actor.");
      return;
    }

    const expertises = actor.system.expertises || {};
    const allConfig = [...EXPERTISES_CONFIG.general, ...EXPERTISES_CONFIG.spellcasting, ...EXPERTISES_CONFIG.weapon];
    const available = [];

    for (const conf of allConfig) {
      const exp = expertises[conf.key];
      if (exp && typeof exp === "object" && Number(exp.value) > 0) {
        available.push({
          key: conf.key,
          label: conf.label,
          hint: conf.hint,
          value: Number(exp.value),
          max: Number(exp.max)
        });
      }
    }

    if (available.length === 0) {
      ui.notifications.warn(`${actor.name} has no remaining expertise uses!`);
      return;
    }

    const currentTier = parseInt(btn.data("currentTier"), 10) || 1;
    if (currentTier >= 3) {
      ui.notifications.info("This test is already at the maximum result of Tier 3.");
      return;
    }

    const nextTier = currentTier + 1;
    let nextTierName = `Tier ${nextTier}: Full Success`;
    if (nextTier === 2) nextTierName = "Tier 2: Partial / Cost Success";
    else if (nextTier === 3) nextTierName = "Tier 3: Superior Success";

    const optionsHtml = available.map(a => `<option value="${a.key}">${a.label} (${a.value}/${a.max} uses) — ${a.hint}</option>`).join("");

    new Dialog({
      title: `Apply Expertise: +1 Tier`,
      content: `
        <form class="crows-dialog-form">
          <p style="margin-bottom: 8px; font-size: 0.85rem;">
            Discuss with the Ref to apply an expertise. Spending 1 use upgrades this roll from <strong>Tier ${currentTier}</strong> ➔ <strong>Tier ${nextTier}</strong>.
          </p>
          <div class="form-group">
            <label>Select Expertise:</label>
            <select id="selected-expertise" style="width: 100%;">
              ${optionsHtml}
            </select>
          </div>
        </form>
      `,
      buttons: {
        apply: {
          icon: '<i class="fas fa-arrow-alt-circle-up"></i>',
          label: `Upgrade to Tier ${nextTier}`,
          callback: async (dHtml) => {
            const expKey = dHtml.find("#selected-expertise").val();
            const expObj = available.find(a => a.key === expKey);
            const spendRes = await actor.spendExpertise(expKey);
            if (!spendRes.success) return;

            // Update chat message content
            const rollCard = $("<div>").html(message.content);
            const outcomeDiv = rollCard.find(".outcome");
            
            outcomeDiv.removeClass("failure mixed doom success crit");
            outcomeDiv.addClass(nextTier === 3 ? "crit" : "success");
            outcomeDiv.text(nextTierName);

            // If it's a weapon attack with damage blocks
            const weaponId = btn.data("itemId");
            const charKey = btn.data("charKey") || "strength";
            let newNumericDmg = 0;
            if (weaponId) {
              const weapon = actor.items.get(weaponId);
              if (weapon && weapon.system.isWeapon) {
                const rawDmg = nextTier === 3 
                  ? (weapon.system.weapon?.tier3Damage || "Tier 3 Damage")
                  : (weapon.system.weapon?.tier2Damage || "Tier 2 Damage");
                const newDmg = actor.evaluateWeaponDamage ? actor.evaluateWeaponDamage(rawDmg, charKey) : rawDmg;
                rollCard.find(".damage-block").html(`<strong>Damage / Effect:</strong> ${newDmg}`);
                newNumericDmg = actor.extractDamageNumber ? actor.extractDamageNumber(rawDmg, charKey) : 0;
              }
            }

            const expertiseBadgeHtml = `
              <div class="expertise-applied-tag" style="margin-top: 4px; margin-bottom: 4px; padding: 4px 8px; background: rgba(124, 58, 237, 0.25); border: 1px solid rgba(168, 85, 247, 0.5); border-radius: 4px; font-size: 0.8rem; color: #e9d5ff;">
                <i class="fas fa-sparkles"></i> <strong>${expObj.label}</strong> applied by ${actor.name} (+1 Tier) &bull; ${spendRes.remaining}/${spendRes.max} uses remaining
              </div>
            `;

            let actionsContainer = rollCard.find(".crows-chat-actions");
            if (actionsContainer.length === 0) {
              rollCard.find(".card-body").append(`<div class="crows-chat-actions flexcol" style="margin-top: 8px; gap: 4px;"></div>`);
              actionsContainer = rollCard.find(".crows-chat-actions");
            }

            // Replace the expertise button with the applied tag
            actionsContainer.find(".crows-apply-expertise-btn").replaceWith(expertiseBadgeHtml);

            // Update or generate damage buttons
            const existingDamageBtns = actionsContainer.find(".crows-apply-damage-btn");
            if (newNumericDmg > 0) {
              if (existingDamageBtns.length > 0) {
                existingDamageBtns.each(function() {
                  const $dmgBtn = $(this);
                  $dmgBtn.attr("data-damage-amount", newNumericDmg);
                  const targetActorId = $dmgBtn.data("targetActorId");
                  const targetTokenId = $dmgBtn.data("targetTokenId");
                  let targetName = "";
                  if (targetActorId) targetName = game.actors.get(targetActorId)?.name;
                  if (!targetName && targetTokenId) targetName = canvas.tokens.get(targetTokenId)?.name;

                  if (targetName) {
                    $dmgBtn.html(`<i class="fas fa-shield-virus"></i> Apply ${newNumericDmg} Damage to ${targetName}`);
                  } else {
                    $dmgBtn.html(`<i class="fas fa-shield-virus"></i> Apply ${newNumericDmg} Damage to Target`);
                  }
                });
              } else {
                // Generate new button if none existed (e.g. upgraded from Tier 1 Miss)
                const targets = Array.from(game.user.targets || []);
                let newBtnsHtml = "";
                if (targets.length > 0) {
                  newBtnsHtml = targets.map(t => `
                    <button type="button" class="crows-apply-damage-btn btn-chat-damage" data-target-actor-id="${t.actor?.id || ''}" data-target-token-id="${t.id}" data-damage-amount="${newNumericDmg}">
                      <i class="fas fa-shield-virus"></i> Apply ${newNumericDmg} Damage to ${t.name}
                    </button>
                  `).join("");
                } else {
                  newBtnsHtml = `
                    <button type="button" class="crows-apply-damage-btn btn-chat-damage" data-damage-amount="${newNumericDmg}">
                      <i class="fas fa-shield-virus"></i> Apply ${newNumericDmg} Damage to Target
                    </button>
                  `;
                }
                actionsContainer.append(newBtnsHtml);
              }
            }

            await message.update({ content: rollCard.html() });
          }
        },
        cancel: {
          label: "Cancel"
        }
      },
      default: "apply"
    }).render(true);
  });

  // Miasma Chat Handler: Gain Cruelty & Trigger Effect Roll
  html.find(".crows-miasma-gain-cruelty-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const actorId = btn.data("actorId");
    const actor = game.actors.get(actorId) || (message.speaker?.token ? canvas.tokens.get(message.speaker.token)?.actor : null);
    if (!actor) {
      ui.notifications.error("Actor not found.");
      return;
    }
    if (!actor.isOwner && !game.user.isGM) {
      ui.notifications.warn("You do not have permission for this actor.");
      return;
    }

    const newCruelty = await actor.adjustCruelty(1);
    ui.notifications.warn(`${actor.name}'s Cruelty increased to ${newCruelty}!`);
    btn.prop("disabled", true).text(`+1 Cruelty Added (Now ${newCruelty})`);

    // Trigger Miasma effect roll
    if (actor.sheet && actor.sheet._onRollMiasmaEffect) {
      await actor.sheet._onRollMiasmaEffect();
    }
  });

  // Miasma Chat Handler: Clear Cruelty
  html.find(".crows-miasma-clear-cruelty-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const actorId = btn.data("actorId");
    const actor = game.actors.get(actorId) || (message.speaker?.token ? canvas.tokens.get(message.speaker.token)?.actor : null);
    if (!actor) {
      ui.notifications.error("Actor not found.");
      return;
    }
    if (!actor.isOwner && !game.user.isGM) {
      ui.notifications.warn("You do not have permission for this actor.");
      return;
    }

    await actor.clearCruelty();
    ui.notifications.info(`${actor.name} purged all levels of cruelty (Cruelty: 0).`);
    btn.prop("disabled", true).text(`Cruelty Purged to 0`);
  });

  // Miasma Chat Handler: Apply Miasma Effect to Sheet
  html.find(".crows-miasma-apply-effect-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const actorId = btn.data("actorId");
    const actor = game.actors.get(actorId) || (message.speaker?.token ? canvas.tokens.get(message.speaker.token)?.actor : null);
    if (!actor) {
      ui.notifications.error("Actor not found.");
      return;
    }
    if (!actor.isOwner && !game.user.isGM) {
      ui.notifications.warn("You do not have permission for this actor.");
      return;
    }

    const title = btn.data("title");
    const firstEffect = decodeURIComponent(btn.data("first") || "");
    const secondEffect = decodeURIComponent(btn.data("second") || "");
    const rollTotal = parseInt(btn.data("roll"), 10) || 1;

    await actor.addMiasmaEffect({ title, firstEffect, secondEffect, rollTotal });
    ui.notifications.info(`Added "${title}" to ${actor.name}'s active Miasma effects.`);
    btn.prop("disabled", true).html(`<i class="fas fa-check"></i> Added to Character Sheet`);
  });

  // Interactive Chat Handler: Apply Damage to Target Dialog
  html.find(".crows-apply-damage-btn").click(async (ev) => {
    ev.preventDefault();
    const btn = $(ev.currentTarget);
    const damageAmount = parseInt(btn.data("damageAmount"), 10) || 1;
    const targetActorId = btn.data("targetActorId");
    const targetTokenId = btn.data("targetTokenId");

    let targetActor = null;
    if (targetActorId) {
      targetActor = game.actors.get(targetActorId);
    }
    if (!targetActor && targetTokenId) {
      targetActor = canvas.tokens.get(targetTokenId)?.actor;
    }
    if (!targetActor) {
      // Fallback: Currently targeted token by user, or currently controlled token
      targetActor = Array.from(game.user.targets)[0]?.actor || canvas.tokens.controlled[0]?.actor;
    }

    if (!targetActor) {
      ui.notifications.warn("No target specified or currently selected. Please target or select a token to apply damage.");
      return;
    }

    if (!targetActor.isOwner && !game.user.isGM) {
      ui.notifications.warn(`You do not have permission to manage damage for ${targetActor.name}.`);
      return;
    }

    if (targetActor.openDamageAllocationDialog) {
      targetActor.openDamageAllocationDialog(damageAmount);
    } else {
      targetActor.applyDamage(damageAmount);
    }
  });
});

async function helperImportCompendium(jsonPath, packName, packLabel, documentType = "Item") {
  const res = await fetch(jsonPath, { cache: "no-store" });
  if (!res.ok) {
    const msg = `${jsonPath.split("/").pop()} is not present. Generate it with tools/build_all.py (see README.md) before importing.`;
    ui.notifications.error(msg);
    throw new Error(msg);
  }
  const docs = await res.json();

  let pack = game.packs.get(`world.${packName}`);
  if (!pack) {
    pack = await CompendiumCollection.createCompendium({
      label: packLabel,
      name: packName,
      type: documentType
    });
  } else {
    const existingDocs = await pack.getDocuments();
    if (existingDocs.length > 0) {
      await pack.documentClass.deleteDocuments(existingDocs.map(d => d.id), { pack: pack.collection });
    }
  }

  const documentClass = documentType === "Actor" ? Actor : Item;
  const created = await documentClass.createDocuments(docs, { pack: pack.collection });
  return created.length;
}

Hooks.once("ready", () => {
  // Initialize and render the Hourglass Dungeon Turn HUD
  const timerHUD = new CrowsDungeonTimer();
  timerHUD.render(true);

  // Expose system helper utilities
  game.crows = {
    timerHUD: timerHUD,

    /**
     * Hourglass Dungeon Turn Timer API
     */
    timer: {
      start: async () => CrowsDungeonTimer.updateState({ isRunning: true }),
      pause: async () => CrowsDungeonTimer.updateState({ isRunning: false }),
      toggle: async () => {
        const state = CrowsDungeonTimer.getState();
        return CrowsDungeonTimer.updateState({ isRunning: !state.isRunning });
      },
      reset: async () => {
        const state = CrowsDungeonTimer.getState();
        return CrowsDungeonTimer.updateState({
          remainingSeconds: (state.durationMinutes || 30) * 60,
          isRunning: false
        });
      },
      nextTurn: async () => timerHUD.endTurn(),
      show: () => timerHUD.render(true),
      hide: () => timerHUD.close()
    },

    /**
     * Canvas Ground Loot API
     */
    scatterLoot: CrowsLoot.scatterItemsOnCanvas,
    createContainerToken: CrowsLoot.createContainerToken,
    createItemToken: CrowsLoot.createItemTokenOnCanvas,

    /**
     * Rolls a d10 Dungeon Encounter Check (Playtest 2 rule)
     */
    rollEncounterCheck: async (en = 9) => {
      const roll = new Roll("1d10");
      await roll.evaluate();
      const result = roll.total;

      let outcomeHtml = "";
      if (result === 10) {
        outcomeHtml = `<div class="outcome doom"><i class="fas fa-skull-crossbones"></i> IMMEDIATE ENCOUNTER! (Rolled 10)</div>
                       <p class="flavor-sub">Monsters ambush or stumble upon the party right now!</p>`;
      } else if (result >= en) {
        outcomeHtml = `<div class="outcome mixed"><i class="fas fa-exclamation-triangle"></i> ENCOUNTER WARNING (Rolled ${result} &ge; EN ${en})</div>
                       <p class="flavor-sub">The party detects signs/sounds of a coming encounter. The encounter occurs during the next Dungeon Turn.</p>`;
      } else {
        outcomeHtml = `<div class="outcome success"><i class="fas fa-shield-alt"></i> ALL QUIET (Rolled ${result} &lt; EN ${en})</div>
                       <p class="flavor-sub">No encounter this turn.</p>`;
      }

      const content = `
        <div class="crows-roll-card">
          <div class="card-header danger">
            <i class="fas fa-dungeon"></i> Dungeon Encounter Check (EN ${en})
          </div>
          <div class="card-body">
            <div class="dice-roll-total">D10 Check: <strong>${result}</strong> vs EN ${en}</div>
            ${outcomeHtml}
          </div>
        </div>
      `;

      await roll.toMessage({
        flavor: `Dungeon Encounter Check (EN ${en})`,
        content: content
      });
    },

    /**
     * Rolls a 1d6 Chaos Roll for non-doom Tier 1 spellcasting
     */
    rollChaos: async () => {
      const roll = new Roll("1d6");
      await roll.evaluate();
      const result = roll.total;

      let outcomeHtml = "";
      if (result === 1) {
        outcomeHtml = `<div class="outcome doom"><i class="fas fa-bolt"></i> MAGICAL BACKLASH! (Rolled 1)</div>
                       <p class="flavor-sub">Roll 1d100 + Spell Rank on the Backlash Table in The Rules Book!</p>`;
      } else {
        outcomeHtml = `<div class="outcome success"><i class="fas fa-check-circle"></i> SAFE (Rolled ${result})</div>
                       <p class="flavor-sub">The chaos recedes without triggering a backlash.</p>`;
      }

      const content = `
        <div class="crows-roll-card">
          <div class="card-header">
            <i class="fas fa-magic"></i> Chaos Roll (1d6)
          </div>
          <div class="card-body">
            <div class="dice-roll-total">Result: <strong>${result}</strong></div>
            ${outcomeHtml}
          </div>
        </div>
      `;

      await roll.toMessage({
        flavor: `Chaos Roll (1d6)`,
        content: content
      });
    },

    /**
     * Imports Standard Equipment & Spellbooks (Player Accessible)
     */
    importEquipment: async () => {
      if (!game.user.isGM) return ui.notifications.warn("Only the GM can import items.");
      try {
        const count = await helperImportCompendium(
          "systems/fvtt-crows-system/packs/equipment.json",
          "crows-equipment",
          "Crows Equipment & Spellbooks"
        );
        ui.notifications.info(`Successfully imported ${count} items into "Crows Equipment & Spellbooks"!`);
      } catch (err) {
        console.error("Crows | Error importing equipment:", err);
        ui.notifications.error("Failed to import equipment.");
      }
    },

    /**
     * Imports Dungeon Loot & Relics (GM / Secret Discovery)
     */
    importDungeonLoot: async () => {
      if (!game.user.isGM) return ui.notifications.warn("Only the GM can import items.");
      try {
        const count = await helperImportCompendium(
          "systems/fvtt-crows-system/packs/dungeon-loot.json",
          "crows-dungeon-loot",
          "Crows Dungeon Loot & Relics"
        );
        ui.notifications.info(`Successfully imported ${count} items into "Crows Dungeon Loot & Relics"!`);
      } catch (err) {
        console.error("Crows | Error importing dungeon loot:", err);
        ui.notifications.error("Failed to import dungeon loot.");
      }
    },

    /**
     * Imports Trait Trees (Player Accessible)
     */
    importTraits: async () => {
      if (!game.user.isGM) return ui.notifications.warn("Only the GM can import items.");
      try {
        const count = await helperImportCompendium(
          "systems/fvtt-crows-system/packs/traits.json",
          "crows-traits",
          "Crows Trait Trees"
        );
        ui.notifications.info(`Successfully imported ${count} traits into "Crows Trait Trees"!`);
      } catch (err) {
        console.error("Crows | Error importing traits:", err);
        ui.notifications.error("Failed to import traits.");
      }
    },

    /**
     * Imports the Bestiary: animals, humans, monsters, and uniques from The Ref Book (Actor compendium)
     */
    importMonsters: async () => {
      if (!game.user.isGM) return ui.notifications.warn("Only the GM can import actors.");
      try {
        const count = await helperImportCompendium(
          "systems/fvtt-crows-system/packs/monsters.json",
          "crows-bestiary",
          "Crows Bestiary",
          "Actor"
        );
        ui.notifications.info(`Successfully imported ${count} creatures into "Crows Bestiary"!`);
      } catch (err) {
        console.error("Crows | Error importing bestiary:", err);
        ui.notifications.error("Failed to import the bestiary.");
      }
    },

    /**
     * Imports Equipment, Dungeon Loot, Traits, and the Bestiary into separate, dedicated compendiums
     */
    importPlaytestItems: async () => {
      if (!game.user.isGM) return ui.notifications.warn("Only the GM can import items.");
      try {
        const countEq = await helperImportCompendium(
          "systems/fvtt-crows-system/packs/equipment.json",
          "crows-equipment",
          "Crows Equipment & Spellbooks"
        );
        const countLoot = await helperImportCompendium(
          "systems/fvtt-crows-system/packs/dungeon-loot.json",
          "crows-dungeon-loot",
          "Crows Dungeon Loot & Relics"
        );
        const countTraits = await helperImportCompendium(
          "systems/fvtt-crows-system/packs/traits.json",
          "crows-traits",
          "Crows Trait Trees"
        );
        const countMonsters = await helperImportCompendium(
          "systems/fvtt-crows-system/packs/monsters.json",
          "crows-bestiary",
          "Crows Bestiary",
          "Actor"
        );
        ui.notifications.info(`Successfully imported ${countEq} equipment items, ${countLoot} dungeon loot items, ${countTraits} traits, and ${countMonsters} creatures!`);
      } catch (err) {
        console.error("Crows | Error importing playtest items:", err);
        ui.notifications.error("Failed to import playtest items.");
      }
    }
  };
});
